### PR TITLE
Feature/media scan deps

### PR DESCRIPTION
**Pull request by fsbruva**
Here is the branch I'm working on. It updates all the stuff that is c/c++. Please let me know if there are different things I need to change to ensure Solaris compatibility.

I am waiting for Michael to merge the other bugfix pull requests before I send this in.

### CODE REVIEW

**Comment by chincheta0815** [comment]
Wow. A lot of changes.
I fear the work on libmediascan... 
Why are you patching it? There are that much changes that would be okay for changes in the upstream repo.
Anyways, this will take some time for me to check. Is there a way to implement the changes step by step?

**Comment by chincheta0815** [comment]
Just an addition:
The best would really be to add the mediascan patches to the upstream libmediascan (https://github.com/andygrundman/libmediascan). A lot of you changes (db, ffmpeg, png, etc. are related to libmediascan anyway...)
Or fork that and implement the changes. That actually was something I always wanted to do It seems the cleanest way.
I think Michael will kill us one day when we just patch the slimserver-vendor.git - it will be messed up one day...

**Comment by chincheta0815** [comment]
I started adding the patches into libmediascan.
Therefore I am using compiler preprocessor defines...
For Solaris I know what to do ;o)
A question: Is the patch for freebsd only needed if the system is freebsd?

**Comment by chincheta0815** [comment]
Sorry for bothering again…
Another few questions came up:
The freebsd patch just sets an „#else“… Don’t you need a compiler define for freedsb there?
The Makefile.PL patch changes a lot push to unshift. Is that only needed for compiling under lms oder do all push have to be changed to unshift as a general solution?

Sorry for bothering I just want to do the things correct… ;o)

**Comment by fsbruva** [comment]
First... are you manually making the changes? You should download it all and see if it works https://help.github.com/articles/checking-out-pull-requests-locally/.

**Comment by fsbruva** [comment]
About libmediascan -
Q: Why are you patching it?
A: The ffmpeg API changed a lot. So did giflib.
Q: Is there a way to implement the changes step by step?
A: Not really. Changing giflib requires changes to libmediascan, as well ass requires ImageScan to be updated. I suppose you could omit the db and jpeg upgrades, at first.
Q: The best would really be to add the mediascan patches to the upstream libmediascan
A: You're right. But the upstream author doesnt seem to be interested in fixing the code. There is an unmerged PR that is 3 years old. The author himself opened an issue one year ago describing the changes that I implemented.

**Comment by fsbruva** [comment]
Q: Is the patch for freebsd only needed if the system is freebsd?
A: That file is unchanged in my update. If ffmpeg and libmediascan were built correctly previously on Solaris, then the patch is not needed for Solaris.

**Comment by fsbruva** [comment]
Q: Don’t you need a compiler define for freedsb there?
A: No, because the source code only gets changed on freebsd platforms
Q: (Push to unshift) Is that only needed for compiling under lms oder do all push have to be changed to unshift as a general solution?
A: That seems to be a change in programming convention. I looked at all the changes Andy Grundman made to ImageScale from v0.11 to v0.14, and mimicked them in libmediascan.

**Comment by chincheta0815** [comment]
Okay. Let me try to sum up all my response ;o)

- General: Of course I am not patching everything manually, but I check what you did and wanted to understand the things a little bit.
- Concerning the compiler defines: I am working on implementing the patches for mediascan.c-files. There I saw that freebsd seems to have problems with following symlinks (as did once for solaris). The freebsd patch just hits a workaround by settings this #else, it does not consider the methods for the symlinks. Better would be to change the __linux__ to __unix__. I will implement the changes and check on Solaris then. Unfortunately, I do not have a FreeBSD system.
- Concerning patching ffmpeg, etc.: Okay, then I will also include these patches into libmediascan.
- Concerning the dependencies: I try not to touch them and let them be patches in the first try.
- Concerning the Makefile.PL: That sound reasonable.

Let's see if we manage to clean the buildme up a little bit...

Is it okay to send you an update once I have everything running on Solaris? I would really appreaciate your second eye on that. Maybe you can also check on a different platform (linux, freebsd, win, mac...)

**Comment by chincheta0815** [comment]
Crap.
I did not want to close it...

**Comment by chincheta0815** [comment]
I try this...

**Comment by fsbruva** [comment]
I am sorry if I offended you with my questions - I just wanted to make sure you weren't making it harder than necessary.
Your points about the FreeBSD and Unix patches is well taken. To be honest, I left them alone without much investigation. You are being more thorough, certainly.
Q: Is it okay to send you an update once I have everything running on Solaris? I would really appreciate your second eye on that.
A: Absolutely! I only have/use FreeBSD as my build platform, however.

**Comment by chincheta0815** [comment]
@fsbruva Hey there, I worked on updating the build and added the patches to libmediascan. Would you be so kind to check if it will build on freebsd? Here the branch https://github.com/chincheta0815/slimserver-vendor/tree/upgraded_libmediascan

**Comment by fsbruva** [comment]
Can you please create a PR against my repository?

**Pull request merged**
